### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce-Issues#3880]
in the game when i try to throw my items i cant throw my items and inventorycleaner try to throw that but thats not rendering and after some minut my game crashed, during the game its spam this error

[17:37:11] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:20) [g.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147237_a(NetHandlerPlayClient.java:484) ~[bcy.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.func_148833_a(SourceFile:75) ~[fp.class:?]
	at net.minecraft.network.play.server.S0CPacketSpawnPlayer.func_148833_a(SourceFile:16) ~[fp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:19) ~[g.class:?]
	... 9 more

and here is crash report

[17:42:24] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:450) ~[biu.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:356) ~[biu.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:323) ~[biu.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:870) ~[bfr.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1763) ~[bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580) ~[bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1372) ~[bfk.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051) ~[ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassCastException: net.minecraft.util.Rotations cannot be cast to java.lang.Byte
	at net.minecraft.entity.DataWatcher.func_75683_a(DataWatcher.java:86) ~[pz.class:?]
	at net.minecraft.entity.monster.EntitySlime.func_70809_q(EntitySlime.java:66) ~[wb.class:?]
	at net.minecraft.client.renderer.entity.RenderSlime.func_76986_a(SourceFile:20) ~[bjy.class:?]
	at net.minecraft.client.renderer.entity.RenderSlime.func_76986_a(SourceFile:9) ~[bjy.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:402) ~[biu.class:?]
	... 15 more
[17:42:24] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
  TransformerLoader (LiquidBounce-b73.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 28.07.2020 17:42
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.util.Rotations cannot be cast to java.lang.Byte
	at net.minecraft.entity.DataWatcher.func_75683_a(DataWatcher.java:86)
	at net.minecraft.entity.monster.EntitySlime.func_70809_q(EntitySlime.java:66)
	at net.minecraft.client.renderer.entity.RenderSlime.func_76986_a(SourceFile:20)
	at net.minecraft.client.renderer.entity.RenderSlime.func_76986_a(SourceFile:9)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:402)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:356)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:323)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:870)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1763)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1372)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.func_75683_a(DataWatcher.java:86)
	at net.minecraft.entity.monster.EntitySlime.func_70809_q(EntitySlime.java:66)
	at net.minecraft.client.renderer.entity.RenderSlime.func_76986_a(SourceFile:20)
	at net.minecraft.client.renderer.entity.RenderSlime.func_76986_a(SourceFile:9)

-- Entity being rendered --
Details:
	Entity Type: Slime (net.minecraft.entity.monster.EntitySlime)
	Entity ID: 7049316
	Entity Name: BalпїЅпїЅk
	Entity's Exact location: -27,50, 86,88, 38,50
	Entity's Block location: -28,00,86,00,38,00 - World: (-28,86,38), Chunk: (at 4,5,6 in -2,2; contains blocks -32,0,32 to -17,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderSlime@6f695719
	Location: -55,27,4,30,31,93 - World: (-56,4,31), Chunk: (at 8,0,15 in -4,1; contains blocks -64,0,16 to -49,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 0.0
	Delta: 0.40870613
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:402)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:356)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:323)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:870)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1763)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1580)

-- Affected level --
Details:
	Level name: MpServer
	All players: 4 total; [EntityPlayerSP['icsarabsikarab'/149054, l='MpServer', x=27,61, y=82,77, z=6,59], EntityOtherPlayerMP['Watters2143'/7048445, l='MpServer', x=32,28, y=39,70, z=-21,00], EntityOtherPlayerMP['seifdz25'/7048533, l='MpServer', x=-15,57, y=85,25, z=-24,13], EntityOtherPlayerMP['Flex_Volce'/7048584, l='MpServer', x=-39,84, y=85,00, z=12,13]]
	Chunk stats: MultiplayerChunkCache: 438, 438
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 6,00,109,00,5,00 - World: (6,109,5), Chunk: (at 6,6,5 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4290299 game time, 30000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 67 total; [EntitySlime['BalпїЅпїЅk'/7050088, l='MpServer', x=-41,50, y=85,92, z=12,50], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049582, l='MpServer', x=-16,50, y=84,44, z=-40,50], EntityArrow['Ok'/7049454, l='MpServer', x=-26,56, y=86,00, z=-26,81], EntitySlime['BalпїЅпїЅk'/7049581, l='MpServer', x=-16,50, y=85,92, z=-40,50], EntityArmorStand['пїЅa02:27'/7049580, l='MpServer', x=-16,50, y=85,03, z=-40,50], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7050087, l='MpServer', x=-41,50, y=84,44, z=12,50], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049317, l='MpServer', x=-27,50, y=85,44, z=38,50], EntityArmorStand['пїЅa02:27'/7050085, l='MpServer', x=-41,50, y=85,03, z=12,50], EntityArrow['Ok'/7049727, l='MpServer', x=-20,03, y=85,16, z=-33,19], EntityOtherPlayerMP['Watters2143'/7048445, l='MpServer', x=32,28, y=39,70, z=-21,00], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049463, l='MpServer', x=49,50, y=79,44, z=14,50], EntitySlime['BalпїЅпїЅk'/7049462, l='MpServer', x=49,50, y=80,92, z=14,50], EntityArmorStand['пїЅa02:27'/7049461, l='MpServer', x=49,50, y=80,03, z=14,50], EntitySlime['BalпїЅпїЅk'/7049291, l='MpServer', x=51,50, y=86,92, z=-7,50], EntityArmorStand['пїЅa02:27'/7049290, l='MpServer', x=51,50, y=86,03, z=-7,50], EntityArmorStand['пїЅcEmpty!'/7050184, l='MpServer', x=-41,50, y=84,78, z=12,50], EntityArrow['Ok'/7049935, l='MpServer', x=-29,38, y=87,38, z=-28,97], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049292, l='MpServer', x=51,50, y=85,44, z=-7,50], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049282, l='MpServer', x=51,50, y=85,44, z=16,50], EntityArrow['Ok'/7049666, l='MpServer', x=-18,78, y=84,44, z=-32,97], EntitySlime['BalпїЅпїЅk'/7049281, l='MpServer', x=51,50, y=86,92, z=16,50], EntityArmorStand['пїЅa02:27'/7049280, l='MpServer', x=51,50, y=86,03, z=16,50], EntityArmorStand['пїЅa02:27'/7049307, l='MpServer', x=-20,50, y=86,03, z=45,50], EntityOtherPlayerMP['LEGENDARYICE1'/7048701, l='MpServer', x=28,59, y=82,00, z=6,78], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049309, l='MpServer', x=-20,50, y=85,44, z=45,50], EntitySlime['BalпїЅпїЅk'/7049308, l='MpServer', x=-20,50, y=86,92, z=45,50], EntityOtherPlayerMP['seifdz25'/7048533, l='MpServer', x=-15,57, y=85,25, z=-24,13], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049384, l='MpServer', x=-27,50, y=85,44, z=-29,50], EntityArrow['Ok'/7049505, l='MpServer', x=-27,53, y=86,00, z=-27,22], EntitySlime['BalпїЅпїЅk'/7049383, l='MpServer', x=-27,50, y=86,92, z=-29,50], EntityArmorStand['пїЅa02:27'/7049382, l='MpServer', x=-27,50, y=86,03, z=-29,50], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049531, l='MpServer', x=29,50, y=84,44, z=49,50], EntityPlayerSP['icsarabsikarab'/149054, l='MpServer', x=27,61, y=82,77, z=6,59], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049402, l='MpServer', x=33,50, y=85,44, z=-36,50], EntitySlime['BalпїЅпїЅk'/7049530, l='MpServer', x=29,50, y=85,92, z=49,50], EntityOtherPlayerMP['Watters2143'/7048445, l='MpServer', x=32,28, y=39,70, z=-21,00], EntitySlime['BalпїЅпїЅk'/7049401, l='MpServer', x=33,50, y=86,92, z=-36,50], EntityArmorStand['пїЅa02:27'/7049529, l='MpServer', x=29,50, y=85,03, z=49,50], EntityOtherPlayerMP['vrmu'/7048413, l='MpServer', x=31,66, y=82,00, z=47,00], EntityArmorStand['пїЅa02:27'/7049400, l='MpServer', x=33,50, y=86,03, z=-36,50], EntityOtherPlayerMP['GudLakHavFun'/7048464, l='MpServer', x=-29,84, y=85,00, z=-25,41], EntityOtherPlayerMP['DUMBSKYLOSE'/7048532, l='MpServer', x=5,78, y=200,00, z=-1,25], EntityOtherPlayerMP['KrabiK299'/7048501, l='MpServer', x=-18,53, y=86,00, z=45,13], EntityOtherPlayerMP['leraer540'/7048541, l='MpServer', x=-37,47, y=86,00, z=-3,41], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049395, l='MpServer', x=40,50, y=85,44, z=-29,50], EntityOtherPlayerMP['seifdz25'/7048533, l='MpServer', x=-15,57, y=85,25, z=-24,13], EntitySlime['BalпїЅпїЅk'/7049394, l='MpServer', x=40,50, y=86,92, z=-29,50], EntityOtherPlayerMP['Flex_Volce'/7048584, l='MpServer', x=-39,84, y=85,00, z=12,13], EntityArmorStand['пїЅa02:27'/7049393, l='MpServer', x=40,50, y=86,03, z=-29,50], EntityOtherPlayerMP['darkwolf3243'/7048570, l='MpServer', x=6,50, y=200,00, z=-3,50], EntityOtherPlayerMP['FireHoit'/7048617, l='MpServer', x=-26,91, y=86,00, z=35,06], EntityOtherPlayerMP['fruko1905gs'/7048587, l='MpServer', x=40,63, y=86,00, z=-26,59], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049354, l='MpServer', x=54,50, y=84,44, z=12,50], EntityOtherPlayerMP['Flex_Volce'/7048584, l='MpServer', x=-39,84, y=85,00, z=12,13], EntitySlime['BalпїЅпїЅk'/7049352, l='MpServer', x=54,50, y=85,92, z=12,50], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049479, l='MpServer', x=-31,50, y=84,44, z=-25,50], EntityArmorStand['пїЅa02:27'/7049350, l='MpServer', x=54,50, y=85,03, z=12,50], EntitySlime['BalпїЅпїЅk'/7049478, l='MpServer', x=-31,50, y=85,92, z=-25,50], EntityArmorStand['пїЅa02:27'/7049477, l='MpServer', x=-31,50, y=85,03, z=-25,50], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049375, l='MpServer', x=-20,50, y=85,44, z=-36,50], EntitySlime['BalпїЅпїЅk'/7049374, l='MpServer', x=-20,50, y=86,92, z=-36,50], EntityArmorStand['пїЅa02:27'/7049373, l='MpServer', x=-20,50, y=86,03, z=-36,50], EntitySlime['BalпїЅпїЅk'/7049363, l='MpServer', x=33,50, y=86,92, z=45,50], EntityArmorStand['пїЅa02:27'/7049361, l='MpServer', x=33,50, y=86,03, z=45,50], EntityItem['item.item.swordStone'/7049623, l='MpServer', x=50,38, y=85,00, z=14,09], EntityItem['item.item.swordIron'/7049622, l='MpServer', x=50,97, y=85,00, z=13,69], EntityArmorStand['ZпїЅrh AskпїЅsпїЅ'/7049365, l='MpServer', x=33,50, y=85,44, z=45,50]]
	Retry entities: 0 total; []
	Server brand: FlameCord <- PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5046637880 bytes (4812 MB) / 5536481280 bytes (5280 MB) up to 6341787648 bytes (6048 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx6022M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
  com.creativemd.itemphysic.ItemTransformer
TransformerLoader (LiquidBounce-b73.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 0' Renderer: 'AMD Radeon HD 7670M'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7670M GL version 4.5.13397 Compatibility Profile Context 0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: TпїЅrkпїЅe (TпїЅrkiye)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13397 Compatibility Profile Context 0
	OpenGlRenderer: AMD Radeon HD 7670M
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
[17:42:24] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Pc\AppData\Roaming\.minecraft\crash-reports\crash-2020-07-28_17.42.24-client.txt
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (258 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] [Crash] Found crash report file: C:\Users\Pc\AppData\Roaming\.minecraft\crash-reports\crash-2020-07-28_17.42.24-client.txt
[Crash] Found crash report file: C:\Users\Pc\AppData\Roaming\.minecraft\crash-reports\crash-2020-07-28_17.42.24-client.txt
flush now

**Comment by lolmc1982** [comment]
Java Version: *1.8.0_51*

**Comment by lolmc1982** [comment]
install new java

**Comment by Teals53** [comment]
thats fix my problem ?
